run-native:
    cargo run --features native

run-native-cn:
    cargo run --features native -- --lang zh-CN

build-web:
    cargo build --features web --target wasm32-unknown-unknown
    wasm-bindgen --out-dir dist --out-name notation_viewer --target web --no-typescript ../../target/wasm32-unknown-unknown/debug/notation_viewer.wasm

run-web:
    just build-web
    basic-http-server -x -a 0.0.0.0:4000

release-web:
    #!/usr/bin/env bash
    set -eu
    cargo build --features web --target wasm32-unknown-unknown --release
    wasm-bindgen --out-dir dist --out-name notation_viewer --target web --no-typescript ../../target/wasm32-unknown-unknown/release/notation_viewer.wasm
    echo "# Before wasm-opt"
    ls -l ./dist/notation_viewer_bg.wasm
    # wasm-opt -Os -o ./dist/notation_viewer_bg.opt.wasm ./dist/notation_viewer_bg.wasm
    wasm-opt -Oz -o ./dist/notation_viewer_bg.opt.wasm ./dist/notation_viewer_bg.wasm
    echo "# After wasm-opt"
    ls -l ./dist/notation_viewer_bg.opt.wasm
    DATE=$(date -u +%Y-%m-%d)
    HASH=$(md5sum ./dist/notation_viewer_bg.opt.wasm | cut -d ' ' -f1)
    echo $HASH
    rm ../../public/notation/*.wasm
    mv -v ./dist/notation_viewer_bg.opt.wasm ../../public/notation/notation_viewer_bg_${DATE}_${HASH}.wasm
    ls -l ../../public/notation/notation_viewer_bg_${DATE}_${HASH}.wasm
    cat ./dist/notation_viewer.js | sed "s/notation_viewer_bg.wasm/notation_viewer_bg_${DATE}_${HASH}.wasm/g" > ../../public/notation/notation_viewer.js

release-windows:
    cargo build --release --features native
